### ISSUE TITLE
Hi, Can you provide these files?

### ISSUE THREAD

**Issue by wulixunhua** [nghiapq77/face-recognition-cpp-tensorrt#1]
This a excellent project, the "config.json" have some parameters：
```
"input_embeddingsFile": "../data/test.json",
"input_numImagesFile": "../data/test_count.txt"
```
Can you provide these files? Thanks

**Comment by nghiapq77** [comment]
Hi,
The text file contains total number of embeddings and the json file contains the 512-dim embeddings of known faces. You should generate those files yourself.
The generation code is here: https://github.com/nghiapq77/face-recognition-cpp-tensorrt/blob/master/src/main.cpp#L83#L136

**Comment by wulixunhua** [comment]
@nghiapq77 Thank you, I have sloved it. 
In addition, do you have decreased accuracy of arcface model when you deployed on DS ?

**Comment by nghiapq77** [comment]
I haven't put much work into testing the accuracy.  I use FP16 precision for both engines and I think there shouldn't be a huge accuracy drop. You can toy with it I guess.
I'll close this. If you have any other questions, feel free to open new issues. I will try to reply in my free time.

**Comment by arminbiglari** [comment]
hello @wulixunhua, how did you generate those files?
please HELP me!.
