### ISSUE TITLE
how to change arcface-ir50 to arcface mobilefacenet?

### ISSUE THREAD

**Issue by futureflsl** [nghiapq77/face-recognition-cpp-tensorrt#2]
arcface-ir50 weights is to big,how repalce it with arcface mobilefacenet?some code can supply?

**Comment by nghiapq77** [comment]
Hi,
Sorry for the late reply,
If you want to change arcface architecture, you could just convert the weight to serialized TensorRT engine via something like torch2trt_dynamic and use this repo normally.
